# base image
FROM node:10.15.0 as ui-builder

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
RUN npm install
RUN npm install -g @vue/cli
RUN npm install pm2 -g
COPY . /usr/src/app
RUN npm run build

# run bff layer
#COPY  --from=ui-builder /usr/src/app/dist /usr/share/nginx/html

RUN cd /usr/src/app/dist/DCO_Client/server/
WORKDIR "/usr/src/app/dist/DCO_Client/server/"
RUN npm install
#pm2 start npm --name "DCOAPP" -- run start:prod

# start app
CMD pm2-runtime 'npm run start:prod'
#CMD [ "pm2-runtime", "start", "/app/bin/www"]